version: "3"
services:
  react-app:
    image: react-app
    stdin_open: true
    ports:
      - "3000:3000"
    networks: 
      - product-app

  api-server:
    image: api-server
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    networks: 
      - product-app

  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - "27017:27017"
    networks: 
      - product-app
    volumes:
      - mongo-data:/data/db
networks: 
  product-app:
    driver: bridge
volumes: 
  mongo-data:
    driver: local
